<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Place;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arr = array(
            array(
                "name" => "Alun-Alun Bandung", 
                "type_place_id" => 1, 
                "rate" => 4.6, 
                "description" => "Tempat ini berwujud taman luas yang dilengkapi air mancur sebagai salah satu simbol Bandung.", 
                "image_name" => "Situs Cagar Budaya_Alun-Alun Bandung", 
                "alamat" => "Jl. Asia-Afrika,Balonggede,Regol", 
                "latitude" => "-6.92193578", 
                "longitude" => "107.6068796"), 
            array(
                "name" => "Taman Maluku (Molukken Park)", 
                "type_place_id" => 1, 
                "rate" => 4.5, 
                "description" => "Taman Maluku adalah salah satu taman di Kota Bandung yang sudah ada sejak jaman penjajahan. Taman ini dibangun pada 1919 oleh pemerintah Hindia Belanda. Nama aslinya adalah Molluken Park. Tadinya taman ini tanah kosong yang berada di Jalan Maluku.", 
                "image_name" => "Situs Cagar Budaya_Taman Maluku (Molukken Park)", 
                "alamat" => "Jl. Ambon,Citarum,Bandung Wetan", 
                "latitude" => "-6.908041305", 
                "longitude" => "107.6149513"), 
            array(
                "name" => "Taman Lalu Lintas AISN (EX-Insulinde Park)", 
                "type_place_id" => 1, 
                "rate" => 4.4, 
                "description" => "Taman Lalu Lintas Bandung merupakan salah satu obyek wisata taman tematik yang cukup terkenal. Taman ini menjadi ikon kota Bandung mengingat usianya yang lebih dari setengah abad.", 
                "image_name" => "Situs Cagar Budaya_Taman Lalu Lintas AISN (EX-Insulinde Park)", 
                "alamat" => "Jl. Belitung No. 1,Merdeka,Sumur", 
                "latitude" => "-6.911338944", 
                "longitude" => "107.6131494"), 
            array(
                "name" => "Taman Lansia", 
                "type_place_id" => 1, 
                "rate" => 4.4, 
                "description" => "Taman kota ini begitu asri dengan pepohonan rindang yang tentunya sudah berumur puluhan tahun. Pohon – pohon ini menjadi peneduh dan penghalau polusi kota. Angin sepoi – sepoi yang menyejukkan akan menemani langkah kaki pengunjung ketika menyusuri jalan setapak taman", 
                "image_name" => "Situs Cagar Budaya_Taman Lansia", 
                "alamat" => "Jl. Cisangkuy/Cilaki,Citarum,Bandung Wetan", 
                "latitude" => "-6.901899494", 
                "longitude" => "107.6209339"), 
            array(
                "name" => "Taman Pustaka Bunga (Kandaga Puspa)", 
                "type_place_id" => 1, 
                "rate" => 4.3, 
                "description" => "Taman Pustaka Bunga Kandaga Puspa memiliki banyak jenis bunga yang menarik. Beberapa jenis bunga yang ada di taman ini adalah mawar, puring, bakung, kastuba, bunga kertas, krisan, lidah mertua dan berbagai jenis anggerk. Beberapa anggrek langka ditemukan di tempat ini. ", 
                "image_name" => "Situs Cagar Budaya_Taman Pustaka Bunga (Kandaga Puspa)", 
                "alamat" => "Jl. Citarum,Citarum,Bandung Wetan", 
                "latitude" => "-6.902212009", 
                "longitude" => "107.622591"), 
            array(
                "name" => "Bandara Husein Sastranegara (EX- Lapangan Terbang Andir)", 
                "type_place_id" => 1, 
                "rate" => 4.5, 
                "description" => "Pada awalnya Bandar Udara Husein Sastranegara merupakan sebuah peninggalan Pemerintah Hindia Belanda dengan sebutan Lapangan Terbang Andir, yaitu suatu nama lokasi di mana lapangan terbang tersebut berada. Nama Husein Sastranegara diambil dari nama seorang pilot militer AURI yang telah gugur pada saat latihan terbang di Yogyakarta tangal 26 September 1946. Pada masa penjajahan Jepang daerah tersebut dijadikan basis Pasukan Udara Angkatan Darat Kekaisaran Jepang.", 
                "image_name" => "Situs Cagar Budaya_Bandara Husein Sastranegara (EX- Lapangan Terbang Andir)", 
                "alamat" => "Jl. Pajajaran,Husein", 
                "latitude" => "-6.899943135", 
                "longitude" => "107.5769371"), 
            array(
                "name" => "Alun-Alun Ujungberung", 
                "type_place_id" => 1, 
                "rate" => 4.4, 
                "description" => "Alun-Alun Ujung Berung menjadi salah satu lokasi wisata yang banyak digemari masyarakat Bandung dan sekitarnya. Salah satunya karena rekreasi ke taman kota ini tidak perlu mengeluarkan banyak biaya. Fasilitas yang tersedia juga tergolong lengkap, mulai dari gazebo, bangku taman, sampai jogging track. Selain itu, terdapat jalur batu-batu refleksi untuk pengobatan dan memelihara kesehatan.", 
                "image_name" => "Situs Cagar Budaya_-Alun-Alun Ujungberung", 
                "alamat" => "Jl. Raya Ujungberung- Cigending,Cigending,Ujungberung", 
                "latitude" => "-6.912770547", 
                "longitude" => "107.7016424"), 
            array(
                "name" => "Saung Angklung Udjo", 
                "type_place_id" => 1, 
                "rate" => 4.7, 
                "description" => "Saung Angklung Udjo (SAU) adalah suatu tempat yang merupakan tempat pertunjukan, pusat kerajinan tangan dari bambu, dan workshop instrumen musik dari bambu. Selain itu, SAU mempunyai tujuan sebagai laboratorium kependidikan dan pusat belajar untuk memelihara kebudayaan Sunda dan khususnya angklung.", 
                "image_name" => "Situs Cagar Budaya_Saung Angklung Udjo", 
                "alamat" => "Jl. Padasuka No. 118,Pasirlayung,Cibeunying Kidul", 
                "latitude" => "-6.89636102", 
                "longitude" => "107.6552254"), 
            array(
                "name" => "Stadion Siliwangi", 
                "type_place_id" => 1, 
                "rate" => 4.4, 
                "description" => "Stadion Siliwangi adalah sebuah stadion yang berada di kota Bandung, Jawa Barat. Stadion ini berada di Jl. Lombok, Bandung.", 
                "image_name" => "Situs Cagar Budaya_Stadion Siliwangi", 
                "alamat" => "Jl. Lombok No. 10,Merdeka,Sumur Bandung", 
                "latitude" => "-6.909381937", 
                "longitude" => "107.6188164"), 
            array(
                "name" => "Taman Musik Centrum", 
                "type_place_id" => 1, 
                "rate" => 3.5, 
                "description" => "Taman Musik Kota Bandung berlokasi tepat di samping Sekolah Menengah Atas Negeri Bandung, SMAN 5. Karena itulah dulu sering digunakan sebagai tempat kumpul, main musik maupun basket para siswa sekolah tersebut.", 
                "image_name" => "Situs Cagar Budaya_Taman Musik Centrum", 
                "alamat" => "Jl. Sumbawa,Merdeka,Sumur Bandung", 
                "latitude" => "-6.910649229", 
                "longitude" => "107.6164134"), 
            array(
                "name" => "The Trans Luxury Hotel ", 
                "type_place_id" => 2, 
                "rate" => 4.7, 
                "description" => "The Trans Luxury Hotel adalah salah satu hotel di Bandung yang terletak bersebelahan dengan Trans Studi Bandung", 
                "image_name" => "Hotel_The Trans Luxury Hotel ", 
                "alamat" => "Jl. Jenderal Gatot Subroto No 289 Bandung Kota Bandung", 
                "latitude" => "-6.926567193", 
                "longitude" => "107.6360264"), 
            array(
                "name" => "Aryaduta Bandung ", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Hotel Aryaduta Bandung merupakan sebuah hotel kelas atas di Bandung. Hotel ini terletak di jantung kota dan menawarkan beragam jenis kamar yang elegan, fasilitas ruang rapat, pusat kebugaran, hiburan, serta menjadi lokasi yang ideal untuk bersantai bagi wisatawan, pelaku bisnis, dan peserta rapat perusahaan.", 
                "image_name" => "Hotel_Aryaduta Bandung ", 
                "alamat" => "Jl. Sumatera No. 51 Bandung Indonesia", 
                "latitude" => "-6.908554243", 
                "longitude" => "107.6118499"), 
            array(
                "name" => "Crowne Plaza Bandung", 
                "type_place_id" => 2, 
                "rate" => 4.6, 
                "description" => "Crowne Plaza Bandung adalah hotel bintang 5 yang terletak sempurna di pusat kota, dekat dengan jalan Braga dan jalan Asia Afrika. Lokasi strategis yang memenuhi standar fasilitas dan layanan IHG (InterContinental Hotel Groups) menawarkan jaminan pertemuan yang lancar dan pengalaman liburan bagi wisatawan modern.", 
                "image_name" => "Hotel_Crowne Plaza Bandung", 
                "alamat" => "Jl. Lembong No.19 Bandung Indonesia", 
                "latitude" => "-6.916165054", 
                "longitude" => "107.6118045"), 
            array(
                "name" => "Prama Grand Preanger Bandung", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Grand Hotel Preanger Bandung dibuka pada tahun 1920 dan kini hotel ini memadukan keanggunan kolonial dengan fasilitas modern dan hotel mewah. Hotel ini terletak di pusat kota dan dekat dengan berbagai lokasi menarik, pusat perbelanjaan, kawasan bisnis di London yang merupakan kota terbesar ketiga di Indonesia. Para tamu dapat bersantai dan nyaman dengan standar tinggi layanan dan fasilitas yang tersedia, mulai dari kamar dan suite hingga berbagai pilihan makanan lokal dan internasional yang disajikan di tiga restoran yang terletak di hotel. Grand Hotel Preanger Bandung juga memiliki fasilitas bisnis dan konferensi yang luas, menjadikannya pilihan yang tepat untuk seminar dan rapat perusahaan. Ada sembilan pilihan ruang pertemuan yang bisa menampung hingga 900 tamu. Grand Hotel Preanger Bandung adalah Hotel berbintang 5 pertama di Jawa Barat sejak tahun 1989.", 
                "image_name" => "Hotel_Prama Grand Preanger Bandung", 
                "alamat" => "Jl. Asia Afrika No.81 Bandung", 
                "latitude" => "-6.919994056", 
                "longitude" => "107.6117737"), 
            array(
                "name" => "G.H Universal", 
                "type_place_id" => 2, 
                "rate" => 4.6, 
                "description" => "G.H. Universal Hotel Bandung adalah hotel bintang lima yang terletak di utara Kota Bandung dekat dengan tempat wisata. Hotel ini dirancang khusus untuk para pelancong yang mengutamakan kemewahan dan kenyamanan dengan 105 kamar dan 9 ruang pertemuan, dilengkapi dengan Courtyard of The Royale Swimming Pool, Spa, Kids Cub, Fat Dragon Chinese Restaurant, Belle Vue 24 Hours French & Italian Bistro, dan satu-satunya hotel hewan peliharaan di Indonesia, GH Penginapan Hewan Peliharaan Universal.", 
                "image_name" => "Hotel_G.H Universal", 
                "alamat" => "Jl.Setiabudhi No.376 Bandung", 
                "latitude" => "-6.849690532", 
                "longitude" => "107.5980558"), 
            array(
                "name" => "Grand Tjokro Bandung", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Grand Tjokro Bandung merupakan salah satu hotel yang terletak di pusat kota bandung", 
                "image_name" => "Hotel_Grand Tjokro Bandung", 
                "alamat" => "Jl. Cihampelas No. 211-217 Bandung Jawa Barat", 
                "latitude" => "-6.885338187", 
                "longitude" => "107.6037964"), 
            array(
                "name" => "Courtyard By Marriott Bandung Dago", 
                "type_place_id" => 2, 
                "rate" => 4.6, 
                "description" => "Berlokasi strategis di jantung pusat kota Bandung yang semarak, akomodasi kami menawarkan kenyamanan modern dengan keanggunan kontemporer di Courtyard Bandung Dago di Indonesia. Kelilingi diri Anda dengan atraksi menarik termasuk Stasiun Bandung, Museum Gedung Sate, dan Stasiun Kereta Api Gedung. Capai tujuan tertinggi Anda di ruang acara canggih untuk rapat, konferensi, dan acara perusahaan", 
                "image_name" => "Hotel_Courtyard By Marriott Bandung Dago", 
                "alamat" => "Jl. Ir. H. Juanda No 31 - 33 Bandung Wetan 40116 Bandung Indonesia", 
                "latitude" => "-6.903293924", 
                "longitude" => "107.6104552"), 
            array(
                "name" => "Garden Permata Hotel", 
                "type_place_id" => 2, 
                "rate" => 5.0, 
                "description" => "Garden Permata Hotel merupakan salah satu hotel yang terletak di pusat kota bandung", 
                "image_name" => "Hotel_Garden Permata Hotel", 
                "alamat" => "Jl. Lemahnendeut No 7 Pasteur Bandung", 
                "latitude" => "-6.882861502", 
                "longitude" => "107.5804462"), 
            array(
                "name" => " El Royale Hotel", 
                "type_place_id" => 2, 
                "rate" => 4.6, 
                "description" => "éL Hotel Royale Bandung terletak dalam jarak berjalan kaki dari Jalan Braga yang bersejarah (Jalan Braga). Hotel ini menyediakan Wi-Fi gratis, restoran, dan ATM untuk kenyamanan Anda. Menikmati lokasi sentral di Bandung, éL Hotel Royale Bandung menawarkan akses mudah ke Museum Asia Afrika. Properti ini berjarak 5 menit berkendara dari kawasan bisnis Bandung dan 15 menit berkendara dari Bandara Internasional Husein Sastranegara.", 
                "image_name" => "Hotel_ El Royale Hotel", 
                "alamat" => "Jl. Merdeka No. 2 Bandung Jawa Barat", 
                "latitude" => "-6.915348358", 
                "longitude" => "107.6104461"), 
            array(
                "name" => "Aston Pasteur", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Terletak di gerbang utama Kota Bandung, ASTON Pasteur Hotel menyambut Anda di ibu kota Jawa Barat yang juga dikenal sebagai Paris van Java. Hotel ini berlokasi strategis di kawasan Pasteur, hanya lima menit dari pintu tol.", 
                "image_name" => "Hotel_Aston Pasteur", 
                "alamat" => "Jl. Dr. Djunjunan 162 Pasteur Bandung Jawa Barat", 
                "latitude" => "-6.892526597", 
                "longitude" => "107.5870908"), 
            array(
                "name" => "Grand Paradise Hotel", 
                "type_place_id" => 2, 
                "rate" => 4.1, 
                "description" => "Grand Paradise Hotel Lembang adalah pilihan yang sangat baik bagi wisatawan yang mengunjungi Bandung, menawarkan lingkungan yang ramah keluarga di samping banyak fasilitas bermanfaat yang dirancang untuk meningkatkan masa inap Anda.", 
                "image_name" => "Hotel_Grand Paradise Hotel", 
                "alamat" => "Jl.Raya Tangkuban Perahu No.50LembangBandung", 
                "latitude" => "-6.809788108", 
                "longitude" => "107.6249132"), 
            array(
                "name" => "Grand Hotel Lembang", 
                "type_place_id" => 2, 
                "rate" => 4.0, 
                "description" => "Grand Hotel Lembang merupakan salah satu hotel yang ada di Bandung dan terletak di daerah yang dekat dengan banyak objek wisata di Lembang", 
                "image_name" => "Hotel_Grand Hotel Lembang", 
                "alamat" => "Jl. Raya Lembang No.272 Lembang Bandung", 
                "latitude" => "-6.814877959", 
                "longitude" => "107.6144734"), 
            array(
                "name" => "The Summit Siliwangi Hotel", 
                "type_place_id" => 2, 
                "rate" => 4.3, 
                "description" => "The Summit Siliwangi Hotel adalah pilihan yang sempurna bagi wisatawan yang ingin menikmati pemandangan dan suasana kota Bandung. Rasakan pelarian perkotaan di Bandung dengan menginap di The Summit Siliwangi Hotel, dengan lokasinya yang luar biasa tepat di pusat kota.", 
                "image_name" => "Hotel_The Summit Siliwangi Hotel", 
                "alamat" => "Jl. Seram No.5 Riau Bandung", 
                "latitude" => "-6.906646416", 
                "longitude" => "107.612606"), 
            array(
                "name" => "D'Best Hotel Pasar Baru ", 
                "type_place_id" => 2, 
                "rate" => 4.2, 
                "description" => "D'best Hotel Bandung, terletak hanya beberapa menit dari jantung kota. Fasilitas dan pelayanan yang diberikan oleh D'best Hotel Bandung menjamin pengalaman menginap yang menyenangkan bagi para tamu. Posting foto Anda dan jawab email Anda kapan pun Anda mau, dengan akses internet Wi-Fi gratis dari hotel. Hotel ini menyediakan layanan penyewaan mobil untuk membantu Anda menemukan apa yang Anda inginkan di Bandung. Parkir tersedia dan gratis, disediakan oleh hotel untuk tamu dengan transportasi mereka sendiri.", 
                "image_name" => "Hotel_D'Best Hotel Pasar Baru ", 
                "alamat" => "Jl. Oto Iskandardinata No.460 Astana Anyar Bandung", 
                "latitude" => "-6.928722471", 
                "longitude" => "107.6035283"), 
            array(
                "name" => "Hotel Nalendra Bandung", 
                "type_place_id" => 2, 
                "rate" => 3.8, 
                "description" => "Sebuah hotel bintang 3 yang nyaman di Cihampelas, Bandung Lokasi kami yang dekat dengan Jakarta menarik banyak wisatawan dari seluruh dunia. Hotel kami akan membuat perjalanan Anda lebih hidup dengan hidangan-hidangan terbaik. Ketika hari mulai berakhir, kembalilah ke kamar ber-AC yang dilengkapi dengan kamar mandi pribadi dan TV kabel. Semuanya tersedia di Hotel Nalendra", 
                "image_name" => "Hotel_Hotel Nalendra Bandung", 
                "alamat" => "Jl.Cihampelas No.225-2229 Bandung", 
                "latitude" => "-6.884766427", 
                "longitude" => "107.6038119"), 
            array(
                "name" => "Wirton Dago Hotel ", 
                "type_place_id" => 2, 
                "rate" => 4.0, 
                "description" => "Pilihan akomodasi yang ideal untuk Pasangan, Backpacker dan Liburan Keluarga. Wirton Dago Hotel sebuah hunian yang berlokasi di Bandung. Suasana ruangan yang bersih dan nyaman, cocok untuk Anda yang akan berlibur atau mengadakan kunjungan bisnis. Lokasi yang strategis sehingga mudah untuk diakses, dan harga yang terjangkau bisa menjadi pilihan akomodasi perjalanan Anda", 
                "image_name" => "Hotel_Wirton Dago Hotel ", 
                "alamat" => "JL. Ir. H. Djuanda No. 395 Dago  Bandung Jawa Barat", 
                "latitude" => "-6.868456796", 
                "longitude" => "107.6197137"), 
            array(
                "name" => "Red Doorz Cibogo Bawah", 
                "type_place_id" => 2, 
                "rate" => 3.9, 
                "description" => "Red Doorz Ciboog Bawah merupakan akomodasi yang berlokasi di kawasan Pasteur, Bandung.", 
                "image_name" => "Hotel_Red Doorz Cibogo Bawah", 
                "alamat" => "Jl. Cibogo Bawah 23-25 Bandung Pasteur", 
                "latitude" => "-6.888485016", 
                "longitude" => "107.5793647"), 
            array(
                "name" => "Bantal Guling Asia Afrika", 
                "type_place_id" => 2, 
                "rate" => 4.0, 
                "description" => "Terletak di Bandung, dalam jarak 13 menit berjalan kaki dari Istana Merdeka dan 1,8 km dari Braga City Walk, Bantal Guling Asia Afrika menyediakan akomodasi dengan taman dan gratis.", 
                "image_name" => "Hotel_Bantal Guling Asia Afrika", 
                "alamat" => "Jl. Kautamaan Istri No.30B Bandung", 
                "latitude" => "-6.925464994", 
                "longitude" => "107.605833"), 
            array(
                "name" => "Hotel Cihampelas", 
                "type_place_id" => 2, 
                "rate" => 4.2, 
                "description" => "Hotel Cihampelas merupakan hotel yang terletak di kawasan Cihampelas, dan hotel ini berdekatan dengan Mall Cihampelas Walk dan beberapa pusat oleh-oleh.", 
                "image_name" => "Hotel_Hotel Cihampelas", 
                "alamat" => "Jl. Cihampelas No.179 Cihampelas Bandung Jawa Barat", 
                "latitude" => "-6.887760665", 
                "longitude" => "107.6037004"), 
            array(
                "name" => "Ariandri Residence", 
                "type_place_id" => 2, 
                "rate" => 4.2, 
                "description" => "Sebuah Penginapan yang Nyaman, Lengkap, dan Terjangkau di Bandung Ariandri Residence adalah tempat bermalam yang tepat bagi Anda dan keluarga saat berlibur di Bandung. Berlokasi startegis di pusat kota Bandung dengan akses mudah ke semua tempat-tempat pavorit. Hotel vintage dengan desain kamar yang modern dan memiliki kenyamanan saat beristirahat dan dengan harga terjangkau.Fasilitas penunjang seperti: Restoran dan WiFi di seluruh area.", 
                "image_name" => "Hotel_Ariandri Residence", 
                "alamat" => "Jl. Cilaki No.31 Bandung", 
                "latitude" => "-6.904613215", 
                "longitude" => "107.627307"), 
            array(
                "name" => "Radio Backpacker Guesthouse", 
                "type_place_id" => 2, 
                "rate" => 4.4, 
                "description" => "Penginapan moden yang nyaman dan tenang. Radio Backpacker Guesthouse adalah wisma 7 kamar yang modern, terbuka dan terang, yang dapat dinikmati oleh semua jenis wisatawan. Kami menawarkan kamar dengan kamar mandi bersama atau pribadi (semua dengan air panas). Radio Backpacker Guesthouse memiliki kamar single, twin, dan pribadi, serta kamar asrama dengan 4 tempat tidur dan Wi-Fi gratis.", 
                "image_name" => "Hotel_Radio Backpacker Guesthouse", 
                "alamat" => "Jl. Babakan Radio Mega Asri Blok E3 No.5 Cicendo Bandung", 
                "latitude" => "-6.89058733", 
                "longitude" => "107.5665261"), 
            array(
                "name" => "Hotel Lodaya", 
                "type_place_id" => 2, 
                "rate" => 3.5, 
                "description" => "Hotel bintang 1 yang nyaman di Bandung.", 
                "image_name" => "Hotel_Hotel Lodaya", 
                "alamat" => "Jl. Lodaya No. 83 Burangrang  Lengkong Bandung", 
                "latitude" => "-6.929800672", 
                "longitude" => "107.6229061"), 
            array(
                "name" => "P Hostel", 
                "type_place_id" => 2, 
                "rate" => 4.4, 
                "description" => "Penginapan yang nyaman tamu yang menginap. Hotel yang berlokasi di kawasan semarak, P Hostel Bandung menawarkan kenyamanan, kemudahan akses untuk mengunjungi tempat-tempat yang patut dikunjungi di Bandung. Fasilitas yang tidak kalah dengan hotel berbintang diatasnya seperti air panas, TV layar datar, AC, TV serta akses internet wifi. Masa menginap anda tidak akan terlupa bersama kami.", 
                "image_name" => "Hotel_P Hostel", 
                "alamat" => "Jl. Peta No. 21  Astanaanyar Bandung Jawa Barat", 
                "latitude" => "-6.936705204", 
                "longitude" => "107.6024535"), 
            array(
                "name" => "Gania Hotel", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Gania hotel bintang 1 namun cukup nyaman.", 
                "image_name" => "Hotel_Gania Hotel", 
                "alamat" => "Jl. Veteran No. 30 Sumurbandung Bandung Jawa Barat", 
                "latitude" => "-6.918418967", 
                "longitude" => "107.614649"), 
            array(
                "name" => "Ten House Bandung", 
                "type_place_id" => 2, 
                "rate" => 3.7, 
                "description" => "Ten House Bandung adalah pilihan yang populer di kalangan wisatawan di Bandung, apakah menjelajahi atau hanya lewat. Hotel ini menawarkan kepada para tamu berbagai layanan dan fasilitas yang dirancang untuk memberikan kenyamanan dan kemudahan. Fasilitas seperti WiFi gratis di semua kamar, resepsionis 24 jam, layanan kamar 24 jam, check-in/check-out cepat, Wi-fi di tempat umum tersedia untuk Anda nikmati.", 
                "image_name" => "Hotel_Ten House Bandung", 
                "alamat" => "Jl. Babakan Jeruk I No.10 Pasteur Bandung Jawa Barat", 
                "latitude" => "-6.890451335", 
                "longitude" => "107.5817039"), 
            array(
                "name" => "Asoka Inn", 
                "type_place_id" => 2, 
                "rate" => 4.4, 
                "description" => "Hostel yang tenang dan nyaman di Pasteur, Bandung Berlokasi di Jalan Surya Sumantri Kav 4B, Pasteur. Asoka Inn menyediakan pelayanan yang ramah dan fasilitas modern. Kami waktu memastikan menginap yang menyenangkan bagi para tamu dengan layanan kami yang personal dan berbagai macam fasilitas modern yang tersedia di hostel kami. Lokasinya cukup strategis karena hanya kurang lebih 2 km dengan Bandara Internasional Husein Sastranegara.", 
                "image_name" => "Guest House_Asoka Inn", 
                "alamat" => "Jl. Surya Sumantri Kav 4B Bandung", 
                "latitude" => "-6.879693963", 
                "longitude" => "107.5806041"), 
            array(
                "name" => "Asoka Hotel", 
                "type_place_id" => 2, 
                "rate" => 4.5, 
                "description" => "Akomodasi yang nyaman dan terjangkau di Bandung Lokasi yang strategis di jantung kota Bandung yang dekat dengan pusat pemerintahan, tempat hiburan dan wisata kuliner. Asoka Hotel Bandung memberikan pemandangan kota dari kamar Anda berada. dengan konsep modern, hotel menawarkan kamar yang bersih dan nyaman dengan layanan prima.", 
                "image_name" => "Guest House_Asoka Hotel", 
                "alamat" => "Jl.Lengkong Besar No. 62 Lengkong Bandung", 
                "latitude" => "-6.926983171", 
                "longitude" => "107.6129214"), 
            array(
                "name" => "Jaksa Guest House", 
                "type_place_id" => 2, 
                "rate" => 4.4, 
                "description" => "Guest House Yang Tenang Dan Nyaman di Bandung. Jaksa Guest House Near Alun-Alun Bandung sebuah hunian yang berlokasi di Bandung. Suasana ruangan yang bersih dan nyaman, cocok untuk Anda yang akan berlibur atau mengadakan kunjungan bisnis. Lokasi yang strategis sehingga mudah untuk diakses, dan harga yang terjangkau bisa menjadi pilihan akomodasi perjalanan Anda.", 
                "image_name" => "Guest House_Jaksa Guest House", 
                "alamat" => "Jl. Jaksa No.1 Pungkur Bandung Jawa Barat", 
                "latitude" => "-6.929525486", 
                "longitude" => "107.6044035"), 
            array(
                "name" => "Sakura Guest House", 
                "type_place_id" => 2, 
                "rate" => 4.1, 
                "description" => "Merupakan guest house di Kota Bandung. Guesthouse ini dilengkapi dengan fasilitas penunjang seperti parkiran, listrik air lancar, wifi (jika tersedia), kamar mandi, tempat tidur, lemari, TV, AC dan lainnya. Sakura guest house menawarkan penginapan dengan harga yang murah dan bagus sehingga menjadi salah satu rekomendasi guest house yang recommended di Kota Bandung.", 
                "image_name" => "Guest House_Sakura Guest House", 
                "alamat" => "Jl. Linggawastu No. 3 Dago Coblong Bandung Jawa Barat", 
                "latitude" => "-6.90292977", 
                "longitude" => "107.6052016"), 
            array(
                "name" => "Hotel Progo", 
                "type_place_id" => 2, 
                "rate" => 3.8, 
                "description" => "Hotel Progo adalah pilihan yang sempurna bagi wisatawan yang ingin menikmati pemandangan dan suasana kota Bandung. Rasakan liburan perkotaan di Bandung dengan menginap di Hotel Progo, dengan lokasinya yang luar biasa tepat di pusat kota.", 
                "image_name" => "Guest House_Hotel Progo", 
                "alamat" => "Jl. Progo no. 6 Riau Bandung", 
                "latitude" => "-6.903839113", 
                "longitude" => "107.6171757"), 
            array(
                "name" => "Museum Geologi Bandung", 
                "type_place_id" => 3, 
                "rate" => 4.6, 
                "description" => "Musieum Géologi Bandung didirikan pada 16 Mei 1929[1]. Museum ini telah direnovasi dengan dana bantuan dari JICA (Japan International Cooperation Agency).[2] Setelah mengalami renovasi, Museum Geologi dibuka kembali dan diresmikan oleh Wakil Presiden RI, Megawati Soekarnoputri pada 23 Agustus 2000.[2] Sebagai salah satu monumen bersejarah, museum berada di bawah perlindungan pemerintah dan merupakan peninggalan nasional.", 
                "image_name" => "Museum_Museum Geologi Bandung", 
                "alamat" => "Jl. Diponegoro No. 57", 
                "latitude" => "-6.899267567", 
                "longitude" => "107.6215411"), 
            array(
                "name" => "Museum Gedung Sate", 
                "type_place_id" => 3, 
                "rate" => 4.6, 
                "description" => "Museum Gedung Sate adalah sebuah museum yang berada di Jalan Diponegoro Nomor 22, Citarum, Bandung Wetan, Kota Bandung, Jawa Barat. Museum ini dibangun khusus untuk menjelaskan tentang sejarah Gedung Sate. Informasi lain yang disampaikan tentang Kota Bandung dan provinsi Jawa Barat", 
                "image_name" => "Museum_Museum Gedung Sate", 
                "alamat" => "Jl. Diponegoro No. 22", 
                "latitude" => "-6.901443316", 
                "longitude" => "107.6194115"), 
            array(
                "name" => "Museum Konferensi Asia Afrika", 
                "type_place_id" => 3, 
                "rate" => 4.7, 
                "description" => "Museum KAA, a place where the history of the Asian-African was raised, and the Asian-African Partnership was enforced for the sake of a better future. Based in Bandung, it has the historical values of the Asian-African Conference in 1955.", 
                "image_name" => "Museum_Museum Konferensi Asia Afrika", 
                "alamat" => "Jl. Asia Afrika No. 65", 
                "latitude" => "-6.920560486", 
                "longitude" => "107.6088133"), 
            array(
                "name" => "Museum Pos Indonesia", 
                "type_place_id" => 3, 
                "rate" => 4.5, 
                "description" => "Museum Pos Indonesia terletak di Jalan Cilaki No. 73 Bandung , Jawa Barat. Museum bersejarah ini sudah berdiri sejak zaman Hindia Belanda, tepatnya pada tahun 1933. Awalnya, bangunan yang didesain oleh duo arsitek J. Berger dan Leutdsgebouwdienst ini bernama Pos Telegrap dan Telepon (PTT).", 
                "image_name" => "Museum_Museum Pos Indonesia", 
                "alamat" => "Jl. Cilaki No. 73", 
                "latitude" => "-6.901331251", 
                "longitude" => "107.6194782"), 
            array(
                "name" => "Museum Nike Ardilla", 
                "type_place_id" => 3, 
                "rate" => 4.7, 
                "description" => "Museum Nike Ardilla di bangun di Komplek Arya Graha, Jalan Aria Utama No. 5, Cipamokolan, Rancasari, Kota Bandung, Jawa Barat 40292, Indonesia.", 
                "image_name" => "Museum_Museum Nike Ardilla", 
                "alamat" => "Komp. Arya Graha. Jl. Aria Utama No. 5", 
                "latitude" => "-6.939685202", 
                "longitude" => "107.6722323"), 
            array(
                "name" => "Hall Of Fame Jawa Barat - Panggung Inohong", 
                "type_place_id" => 3, 
                "rate" => 4.7, 
                "description" => "Ruangan dengan luas sekitar 600 meter persegi yang terletak di salah satu sudut Gedung Bapusipda Jabar tersebut diubah menjadi museum Hall of Fame/Panggung Inohong Jawa Barat.", 
                "image_name" => "Museum_Hall Of Fame Jawa Barat - Panggung Inohong", 
                "alamat" => "Bapusipda", 
                "latitude" => "-6.934619788", 
                "longitude" => "107.6623186"), 
            array(
                "name" => "Museum Pendidikan Nasional", 
                "type_place_id" => 3, 
                "rate" => 4.7, 
                "description" => "Museum Pendidikan Nasional Universitas Pendidikan Indonesia adalah sebuah museum yang terletak di Jalan DR. Setiabudhi Nomor 229, Isola, Sukasari, Kota Bandung, Jawa Barat. Fungsi khusus museum ini untuk memberikan informasi mengenai sejarah dan perkembangan pendidikan di Indonesia.", 
                "image_name" => "Museum_Museum Pendidikan Nasional", 
                "alamat" => "Jl. Dr.Setiabudi No. 225", 
                "latitude" => "-6.858639508", 
                "longitude" => "107.5942122"), 
            array(
                "name" => "Gedung Indonesia Menggugat", 
                "type_place_id" => 3, 
                "rate" => 4.5, 
                "description" => "Gedung Indonesia Menggugat terletak di Jalan Perintis Kemerdekaan Nomor 5, Kota Bandung, tidak jauh dari Balai Kota Bandung. Gedung ini memiliki pelataran yang cukup luas dengan satu pohon beringin kokoh yang rindang. Gedung ini menjadi salah satu gedung bersejarah yang terawat dengan baik.", 
                "image_name" => "Museum_Gedung Indonesia Menggugat", 
                "alamat" => "Jl. Perintis Kemerdekaan No. 5", 
                "latitude" => "-6.913101764", 
                "longitude" => "107.6077288"), 
            array(
                "name" => "Museum Perjuangan Rakyat Jawa Barat", 
                "type_place_id" => 3, 
                "rate" => 4.5, 
                "description" => "Monumen Perjuangan Rakyat Jawa Barat (Monju) adalah Museum Sejarah Perjuangan Rakyat Jawa Barat, di Tatar Pasundan atau Parahyangan. Monumen diresmikan oleh Gubernur Jawa Barat, Raden Nana Nuriana pada tanggal 23 Agustus 1995", 
                "image_name" => "Museum_Museum Perjuangan Rakyat Jawa Barat", 
                "alamat" => "Jl. Dipatiukur No. 48", 
                "latitude" => "-6.892452702", 
                "longitude" => "107.6182938"), 
            array(
                "name" => "Museum Barli", 
                "type_place_id" => 3, 
                "rate" => 4.5, 
                "description" => "Museum Barli Bandung sendiri didirikan selain sebagai tempat untuk menampilkan karya seni para seniman bandung,", 
                "image_name" => "Museum_Museum Barli", 
                "alamat" => "Jl. Prof. Dr. Sutami No. 91", 
                "latitude" => "-6.877308577", 
                "longitude" => "107.5873814"), 
            array(
                "name" => "Ciwalk", 
                "type_place_id" => 4, 
                "rate" => 4.6, 
                "description" => "Cihampelas Walk (Ciwalk) adalah salah satu pusat perbelanjaan mewah di Kota Bandung. Mall ini berdiri pada tahun 2004. Berjalan-jalan di Cihampelas pada siang, sore dan malam hari akan berbeda suasananya. Lampu dari tiap gerai dan bangunan utama pada malam hari akan memberikan atmosfer yang berbeda, belum lagi juntaian dan lilitan lampu hias yang digantungkan di pohon-pohon sekitar outdoor Ciwalk.", 
                "image_name" => "Mall_Ciwalk", 
                "alamat" => "Jl. Cihampelas No. 160", 
                "latitude" => "-6.893906195", 
                "longitude" => "107.6040046"), 
            array(
                "name" => "Paris Van Java Resort Lifestyle Place", 
                "type_place_id" => 4, 
                "rate" => 4.6, 
                "description" => "Paris Van Java Resort Lifestyle Place adalah sebuah pusat perbelanjaan yang terletak di Bandung, Jawa Barat. Mal ini bisa dicapai beberapa jam dengan mengemudi dari Tol Pasteur.", 
                "image_name" => "Mall_Paris Van Java Resort Lifestyle Place", 
                "alamat" => "Jl. Sukajadi No. 131-139", 
                "latitude" => "-6.88840101", 
                "longitude" => "107.5959495"), 
            array(
                "name" => "Bandung Indah Plaza", 
                "type_place_id" => 4, 
                "rate" => 4.4, 
                "description" => "Bandung Indah Plaza adalah salah satu pusat perbelanjaan besar di kota Bandung. Mall ini merupakan pusat perbelanjaan tertua di Bandung. Didirikan pada akhir tahun 80-an, mulai buka tahun 1989 dan secara resminya dibuka pada 19 Agustus 1990.", 
                "image_name" => "Mall_Bandung Indah Plaza", 
                "alamat" => "Jl. Merdeka No. 56", 
                "latitude" => "-6.907568829", 
                "longitude" => "107.6108442"), 
            array(
                "name" => "Trans Studio Mall", 
                "type_place_id" => 4, 
                "rate" => 4.5, 
                "description" => "Trans Studio Mall merupakan salah satu mall besar yang berada di Bandung, mall ini terletak di satu kawasan dengan Trans Studio Bandung dan Trans Luxury Hotel.", 
                "image_name" => "Mall_Trans Studio Mall", 
                "alamat" => "Jl. Gatot Subroto No. 289", 
                "latitude" => "-6.925389733", 
                "longitude" => "107.6367056"), 
            array(
                "name" => "Festival Citylink", 
                "type_place_id" => 4, 
                "rate" => 4.5, 
                "description" => "Festival Citylink merupakan salah satu pusat perbelanjaan besar di Bandung yang dibangun oleh Agung Podomoro Land. Terletak di Jalan Peta (Lingkar Selatan). Didirikan pada tahun 2010, mulai dibuka tahun September 2010 dan secara resminya dibuka pada 28 Oktober 2010.", 
                "image_name" => "Mall_Festival Citylink", 
                "alamat" => "Jl. Peta No. 241", 
                "latitude" => "-6.929303607", 
                "longitude" => "107.5865612"), 
            array(
                "name" => "Blossom ", 
                "type_place_id" => 5, 
                "rate" => 4.2, 
                "description" => "Blossom Factory Outlet adalah salah satu pusat belanja aneka produk fashion yang sudah lama terkenal di daerah Dago.", 
                "image_name" => "Outlet_Blossom", 
                "alamat" => "Jl. Ir. H. Juanda No. 112", 
                "latitude" => "-6.89119231", 
                "longitude" => "107.6134214"), 
            array(
                "name" => "Morning Dew Factory Outlet", 
                "type_place_id" => 5, 
                "rate" => 4.1, 
                "description" => "Morning Dew Factory Outlet berlokasi di Bandung, Indonesia. Perusahaan ini berkecimpung dalam aktivitas bisnis Mode, Pakaian dan Asesoris.", 
                "image_name" => "Outlet_Morning Dew Factory Outlet", 
                "alamat" => "Jl. Ir. H. Juanda No. 81", 
                "latitude" => "-6.897052321", 
                "longitude" => "107.6126305"), 
            array(
                "name" => "Paberik Badjoe Factory Outlet", 
                "type_place_id" => 5, 
                "rate" => 4.4, 
                "description" => "Pabrik Badjoe Factory Outlet merupakan toko pakaian yang menjual merk brand nasional terkemuka di Indonesia.", 
                "image_name" => "Outlet_Paberik Badjoe Factory Outlet", 
                "alamat" => "Jl. Soekarno Hatta No. 573", 
                "latitude" => "-6.944860911", 
                "longitude" => "107.6381787"), 
            array(
                "name" => "Adidas Outlet Dago", 
                "type_place_id" => 5, 
                "rate" => 4.3, 
                "description" => "Adidas Outlet Dago merupakan outlet yang menjua sepatu dan barang-barang dengan merk Adidas.", 
                "image_name" => "Outlet_Adidas Outlet Dago", 
                "alamat" => "Jl. Ir H. Juanda No. 123", 
                "latitude" => "-6.890961915", 
                "longitude" => "107.6132616"), 
            array(
                "name" => "Eiger", 
                "type_place_id" => 5, 
                "rate" => 4.7, 
                "description" => "EIGER diluncurkan pertama kali pada tahun 1989 sebagai produk untuk memenuhi berbagai kebutuhan perlengkapan dan peralatan bagi gaya hidup para penggiat alam terbuka.", 
                "image_name" => "Outlet_Eiger", 
                "alamat" => "Jl. Pelajar Pejuang 45 No. 112", 
                "latitude" => "-6.943010906", 
                "longitude" => "107.6294057"), 
            array(
                "name" => "Apple Bee Kid'S", 
                "type_place_id" => 6, 
                "rate" => 3.4, 
                "description" => "Apple Bee Bandung Kids Playground arena bermain dengan beragam wahana permainan seru untuk anak-anak", 
                "image_name" => "Wisata Buatan_Apple Bee Kid'S", 
                "alamat" => "Paris Van Java Jl. Sukajadi No. 131-139", 
                "latitude" => "-6.887875609", 
                "longitude" => "107.5956716"), 
            array(
                "name" => "Next Level", 
                "type_place_id" => 6, 
                "rate" => 4.6, 
                "description" => "Permainan Outbond yang ada di dalam Mall Pertama & Terbesar di Bandung", 
                "image_name" => "Wisata Buatan_Next Level", 
                "alamat" => "Paris Van Java Jl. Sukajadi No. 131-139", 
                "latitude" => "-6.887390858", 
                "longitude" => "107.5955594"), 
            array(
                "name" => "Boulder Trampoline Park", 
                "type_place_id" => 6, 
                "rate" => 4.4, 
                "description" => "Boulder Trampoline Park merupakan tempat wahana bermain yang berisi trampoline dan mainan lainnya", 
                "image_name" => "Wisata Buatan_Boulder Trampoline Park", 
                "alamat" => "Paris Van Java Jl. Sukajadi No. 131-139", 
                "latitude" => "-6.887935176", 
                "longitude" => "107.5959801"), 
            array(
                "name" => "Kidcity Cipadung", 
                "type_place_id" => 6, 
                "rate" => 4.4, 
                "description" => "Kidcity Cipadung merupakan tempat permainan anak-anak yang terletak di dalam pusat perbelanjaan", 
                "image_name" => "Wisata Buatan_Kidcity Cipadung", 
                "alamat" => "Transmart Cipadung Jl. A.H. Nasution No. 73", 
                "latitude" => "-6.924816571", 
                "longitude" => "107.7112179"), 
            array(
                "name" => "D'Fun Station", 
                "type_place_id" => 6, 
                "rate" => 4.3, 
                "description" => "Fun Station merupakan salah satu arena bermain anak-anak terbesar yang menempati area seluas 7.000 m2 yang berlokasi dikawasan bandung selatan dengan konsep indoor dan outdoor playground.un Station merupakan salah satu arena bermain anak-anak terbesar yang menempati area seluas 7.000 m2 yang berlokasi dikawasan bandung selatan dengan konsep indoor dan outdoor playground.", 
                "image_name" => "Wisata Buatan_D'Fun Station", 
                "alamat" => "Jl. Candra Kirana No. 1", 
                "latitude" => "-6.890176824", 
                "longitude" => "107.573461"), 
            array(
                "name" => "Bandung Science Center", 
                "type_place_id" => 6, 
                "rate" => 4.1, 
                "description" => "Science Center merupakan tempat bermain sekaligus wisata edukasi yang berada di Kawasan Budaya Sabilulungan Soreang, Kabupaten Bandung.", 
                "image_name" => "Wisata Buatan_Bandung Science Center", 
                "alamat" => "Jl. Sirnagalih No. 15", 
                "latitude" => "-6.876429263", 
                "longitude" => "107.5945793"), 
            array(
                "name" => "Jurassic Island Metro Indah Mall", 
                "type_place_id" => 6, 
                "rate" => 3.6, 
                "description" => "Jurassic Island Metro Indah Mall merupakan wahana permainan anak-anak yang terletak di dalam pusat berbelanjaan Metro Indah Mall.", 
                "image_name" => "Wisata Buatan_Jurassic Island Metro Indah Mall", 
                "alamat" => "Metro Indah Mall Lt. Ug Blok B3", 
                "latitude" => "-6.941973611", 
                "longitude" => "107.6588373"), 
            array(
                "name" => "Miniapolis Zone", 
                "type_place_id" => 6, 
                "rate" => 4.3, 
                "description" => "Miniapolis Bandung salah satu arena bermain keluarga dengan anak-anak berusia 0 sampai 12 tahun. Tempat ini didesain khusus guna menyesuaikan imajinasi dunia anak yang dilengkapi permainan untuk melatih motorik.", 
                "image_name" => "Wisata Buatan_Miniapolis Zone", 
                "alamat" => "Paris Van Java Lt. Sl Unit. 22", 
                "latitude" => "-6.889494455", 
                "longitude" => "107.5962732"), 
            array(
                "name" => "Game Master Bec", 
                "type_place_id" => 6, 
                "rate" => 4.6, 
                "description" => "Game Master BEC merupakan tempat mandi bola dengan playground yang lumayan luas.", 
                "image_name" => "Wisata Buatan_Game Master Bec", 
                "alamat" => "Jl. Purnawarman No. 13", 
                "latitude" => "-6.907213529", 
                "longitude" => "107.6087082"), 
            array(
                "name" => "Edukidzment", 
                "type_place_id" => 6, 
                "rate" => 4.3, 
                "description" => "Edukidzment sendiri adalah sebuah perusahaan yang menawarkan wisata outbound dan banyak permainan air yang menarik, yang berlokasi di jalan Suryalaya Indah No 1-3, Buah Batu, Kota Bandung Jawa Barat.", 
                "image_name" => "Wisata Buatan_Edukidzment", 
                "alamat" => "Jl. Suryalaya Indah No. 1-3", 
                "latitude" => "-6.942127498", 
                "longitude" => "107.6247694"), 
            array(
                "name" => "Komplek Universitas Pendidikan Indonesia", 
                "type_place_id" => 7, 
                "rate" => 4.7, 
                "description" => "Komplek Universitas Pendidikan Indonesia adalah sebuah perguruan tinggi negeri yang kampus utamanya berkedudukan di Kota Bandung, Jawa Barat, Indonesia. Sejak tahun 2012, UPI berstatus sebagai perguruan tinggi yang diselenggarakan pemerintah (PTP), berubah dari status sebelumnya sebagai perguruan tinggi Badan Hukum Milik Negara (BHMN).", 
                "image_name" => "Wisata Pendidikan dan Sejarah_Komplek Universitas Pendidikan Indonesia", 
                "alamat" => "Jl. Dr. Setiabudi No.229 Isola Kec. Sukasari Kota Bandung Jawa Barat 40154", 
                "latitude" => "-6.86028166", 
                "longitude" => "107.5942211"), 
            array(
                "name" => "Komplek Universitas Padjajaran", 
                "type_place_id" => 7, 
                "rate" => 4.7, 
                "description" => "Komplek Universitas Padjajaran adalah sebuah perguruan tinggi negeri di Bandung, Jawa Barat, Indonesia. Kampus utama Unpad, terutama untuk Program Sarjana, berada di Jatinangor, Kabupaten Sumedang, Jawa Barat.", 
                "image_name" => "Wisata Pendidikan dan Sejarah_Komplek Universitas Padjajaran", 
                "alamat" => "Jl. Dipati Ukur No.35 Lebakgede Kecamatan Coblong Kota Bandung Jawa Barat 40132", 
                "latitude" => "-6.890077671", 
                "longitude" => "107.6178079"), 
            array(
                "name" => "Ganesa ITB", 
                "type_place_id" => 7, 
                "rate" => 4.7, 
                "description" => "Ganesa ITB merupakan komplek Universitas ternamam di Bandung yaitu Institut Teknologi Bandung", 
                "image_name" => "Wisata Pendidikan dan Sejarah_Ganesa ITB", 
                "alamat" => "Jl. Ganesa Lb. Siliwangi Kecamatan Coblong Kota Bandung Jawa Barat 40132", 
                "latitude" => "-6.890499998", 
                "longitude" => "107.6105303"), 
            array(
                "name" => "Museum Geologi Bandung", 
                "type_place_id" => 7, 
                "rate" => 4.6, 
                "description" => "Musieum Géologi Bandung didirikan pada 16 Mei 1929[1]. Museum ini telah direnovasi dengan dana bantuan dari JICA (Japan International Cooperation Agency).[2] Setelah mengalami renovasi, Museum Geologi dibuka kembali dan diresmikan oleh Wakil Presiden RI, Megawati Soekarnoputri pada 23 Agustus 2000.[2] Sebagai salah satu monumen bersejarah, museum berada di bawah perlindungan pemerintah dan merupakan peninggalan nasional.", 
                "image_name" => "Wisata Pendidikan dan Sejarah_Museum Geologi Bandung", 
                "alamat" => "Jl. Diponegoro No. 57", 
                "latitude" => "-6.900077053", 
                "longitude" => "107.6214982"), 
            array(
                "name" => "Museum Gedung Sate", 
                "type_place_id" => 7, 
                "rate" => 4.6, 
                "description" => "Museum Gedung Sate adalah sebuah museum yang berada di Jalan Diponegoro Nomor 22, Citarum, Bandung Wetan, Kota Bandung, Jawa Barat. Museum ini dibangun khusus untuk menjelaskan tentang sejarah Gedung Sate. Informasi lain yang disampaikan tentang Kota Bandung dan provinsi Jawa Barat", 
                "image_name" => "Museum_Museum Gedung Sate", 
                "alamat" => "Jl. Diponegoro No. 22", 
                "latitude" => "-6.901272899", 
                "longitude" => "107.619154"), 
            array(
                "name" => "Mesjid Lautze", 
                "type_place_id" => 8, 
                "rate" => 4.8, 
                "description" => "Masjid Lautze adalah masjid dengan gaya arsitektur Tionghoa yang terletak di Jalan Tamblong No 27, Kota Bandung, dikelola oleh Yayasan Haji Karim Oei (YHKO)", 
                "image_name" => "Wisata Religi_Mesjid Lautze", 
                "alamat" => "Jl. Tamblong No.27 Braga Kec. Sumur Bandung Kota Bandung Jawa Barat 40111", 
                "latitude" => "-6.917154956", 
                "longitude" => "107.6122633"), 
            array(
                "name" => "Mesjid Al-Ukhuwah", 
                "type_place_id" => 8, 
                "rate" => 4.9, 
                "description" => "Mesjid Al-Ukhuwah yang dibangun pada tahun 1970 merupakan kategori masjid besar, memiliki luas tanah 5.000 meter persegi, luas bangunan 5.000 meter persegi.", 
                "image_name" => "Wisata Religi_Mesjid Al-Ukhuwah", 
                "alamat" => "Jl. Wastukencana No.27", 
                "latitude" => "-6.909821138", 
                "longitude" => "107.6085915"), 
            array(
                "name" => "Mesjid Trans Studio Bandung", 
                "type_place_id" => 8, 
                "rate" => 4.8, 
                "description" => "Masjid Agung Trans Studio Bandung yang merupakan salah satu masjid hits di Bandung tentunya mempunyai daya tarik tersendiri bagi siapa saja yang mengunjunginya.", 
                "image_name" => "Wisata Religi_Mesjid Trans Studio Bandung", 
                "alamat" => "Jl. Gatot Subroto No.289 Cibangkong Batununggal Bandung City West Java 40273", 
                "latitude" => "-6.925026171", 
                "longitude" => "107.6353419"), 
            array(
                "name" => "Gereja Katedral", 
                "type_place_id" => 8, 
                "rate" => 4.8, 
                "description" => "Gereja Katedral Bandung, atau Katedral Santo Petrus, adalah sebuah gereja yang terletak di Jalan Merdeka, Babakanciamis, Sumurbandung, Bandung, Indonesia. Bangunan ini dirancang oleh Charles Prosper Wolff Schoemaker dan bergaya arsitektur neo-Gothic akhir. Dilihat dari atas, bentuknya menyerupai salib yang simetris.", 
                "image_name" => "Wisata Religi_Gereja Katedral", 
                "alamat" => "Jl. Merdeka No.14 Babakan Ciamis Kec. Sumur Bandung Kota Bandung Jawa Barat 40117", 
                "latitude" => "-6.91363902", 
                "longitude" => "107.6107108"), 
            array(
                "name" => "Vihara Bandung", 
                "type_place_id" => 8, 
                "rate" => 4.5, 
                "description" => "Vihara Dharma Ramsi yang dibangun pada tahun 1954. Bangunan yang sudah hampir berumur 67 tahun itu masih ada dan hingga sekarang vihara itu digunakan untuk sembahyang umat Buddha. ", 
                "image_name" => "Wisata Religi_Vihara Bandung", 
                "alamat" => "Jl. Vihara No.68 ", 
                "latitude" => "-6.917454565", 
                "longitude" => "107.5932091"), 
            array(
                "name" => "Saung Angklung Udjo", 
                "type_place_id" => 9, 
                "rate" => 4.7, 
                "description" => "Saung Angklung Udjo (SAU) adalah suatu tempat yang merupakan tempat pertunjukan, pusat kerajinan tangan dari bambu, dan workshop instrumen musik dari bambu. Selain itu, SAU mempunyai tujuan sebagai laboratorium kependidikan dan pusat belajar untuk memelihara kebudayaan Sunda dan khususnya angklung.", 
                "image_name" => "Wisata Budaya_Saung Angklung Udjo", 
                "alamat" => "Jl. Padasuka No. 118,Pasirlayung,Cibeunying Kidul", 
                "latitude" => "-6.896488834", 
                "longitude" => "107.6547962"), 
            array(
                "name" => "Dago Tea House", 
                "type_place_id" => 9, 
                "rate" => 4.5, 
                "description" => "Dikenal sebagai Dago Theehuis di zaman Belanda, Dago Tea House menawarkan panorama hamparan lembah Kota Bandung terindah, terutama di malam hari dimana kamu bisa melihat kerlap-kerlip lampu kota yang mempesona dari dataran tinggi Dago. Kamu juga sekaligus bisa menikmati berbagai pagelaran kesenian khas Jawa Barat yang digelar di Taman Budaya Jawa Barat.", 
                "image_name" => "Wisata Budaya_Dago Tea House", 
                "alamat" => "Jl. Bukit Dago Utara III No.9 Dago Kecamatan Coblong Kota Bandung Jawa Barat 40135", 
                "latitude" => "-6.869151854", 
                "longitude" => "107.6166538"), 
            array(
                "name" => "Gedung Pertunjukan Rumentang Siang", 
                "type_place_id" => 9, 
                "rate" => 4.1, 
                "description" => "Gedung Rumentang Siang merupakan cagar budaya yang harus dipelihara. Selain tempat berkesenian di Baranangsiang, di Jalan Naripan juga ada Yayasan Pusat Kesenian (YPK). Tempat ini pun kerap digunakan untuk pagelaran pada seniman Bandung.", 
                "image_name" => "Wisata Budaya_Gedung Pertunjukan Rumentang Siang", 
                "alamat" => "Jl. Baranang Siang No.1 Kb. Pisang Kec. Sumur Bandung Kota Bandung Jawa Barat 40112", 
                "latitude" => "-6.918887365", 
                "longitude" => "107.6211181"), 
            array(
                "name" => "Padepokan Seni Mayang Sunda", 
                "type_place_id" => 9, 
                "rate" => 4.4, 
                "description" => "Padepokan Seni Mayang Sunda sadalah tempat pertunjukan ke senian yang terletak di kota bandung, Tepat nya Gedung ini Berlokasi di Jalan Peta No.209, Suka Asih, Bojongloa Kaler, Kota Bandung, Jawa Barat 40321. Tempat Ini Menjadi Pilihan Komunitas Untuk Berlatih, Diskusi Hingga Menggelar Pertunjukan.", 
                "image_name" => "Wisata Budaya_Padepokan Seni Mayang Sunda", 
                "alamat" => "Jl. Peta No.209 Suka Asih Kec. Bojongloa Kaler Kota Bandung Jawa Barat 40231", 
                "latitude" => "-6.932058188", 
                "longitude" => "107.5898237"), 
            array(
                "name" => "Teras Sunda Cibiru", 
                "type_place_id" => 9, 
                "rate" => 4.5, 
                "description" => "Teras Sunda Cibiru merupakan tempat wisata berbasis seni dan budaya di Kota Bandung yang terletak di Jalan AH. Nasution, Kelurahan Cipadung, Kecamatan Cibiru, Kota Bandung.", 
                "image_name" => "Wisata Budaya_Teras Sunda Cibiru", 
                "alamat" => "Jl. Raya Cipadung Cipadung Kec. Cibiru Kota Bandung Jawa Barat 40614", 
                "latitude" => "-6.92641577", 
                "longitude" => "107.7112583")
        );

        foreach($arr as $data){
            $model = new Place();
            $model->name = $data['name'];
            $model->type_place_id = $data['type_place_id'];
            $model->rate = $data['rate'];
            $model->description = $data['description'];
            // $model->image_name = public_path('img/destination/').$data['image_name'].".jpg";
            $model->image_name = $data['image_name'].".jpg";
            $model->alamat = $data['alamat'];
            $model->latitude = $data['latitude'];
            $model->longitude = $data['longitude'];
            $model->save();
        }
    }
}
